[package]
name = "space_battle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9", features = ["jpeg"] }
bevy_egui = "0.17"
bevy_prototype_debug_lines = { version = "0.9", features = ["3d"] }
bevy_rapier3d = { version = "0.19", features = ["parallel", "simd-stable"] }
bitflags = "1"