[package]
name = "space_battle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy =  { version = "0.6", features = ["jpeg"] }
bevy_egui = "0.11"
#bevy_prototype_debug_lines = "0.3"
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier.git", features = ["parallel", "simd-stable"] }
bitflags = "1"